### ISSUE TITLE
Config Option To Change Stats of Items

### ISSUE THREAD

**Issue by Blunder-G** [infernalstudios/Mining-Master#22]
### Describe the Addition

A config option to change Item' Durability, Base Protection and Toughness, Attack Point and so on. (Item Examples: Paragon Armor, Ultima Sword etc.)

Thx for this amazing mod!

**Comment by Dariensg** [comment]
It's typically a bad idea to make registration based things dependent on a config (so much so that Forge now blocks it from happening). I'm guessing there are mods out there similar to things like CraftTweaker that will let you change stats, but I'm not going to build that into the mod itself.
